/**
 * Válogatott fotók: forrásfájl → slug. A slug lesz a fájlnév a public/images/photos alatt.
 * Ide csak az kerül, ami a kurált fotóelemzésben (docs/PHOTOS.md) átment.
 */
export const SOURCE_ROOT = "/Volumes/Samsung 1TB SSD/Pictures/Képek/2026/Gyűrüs";

export const PHOTOS = [
  { src: "DJI_0719.jpg",  slug: "dron-naplemente-v",      alt: "Drónfelvétel naplementében: lovasok V-alakban a gyűrűsi versenypályán, két oldalt nézők", alt_en: "Drone shot at sunset: riders in a V formation on the competition ground in Gyűrűs, spectators on both sides", alt_de: "Drohnenaufnahme bei Sonnenuntergang: Reiter in V-Formation auf dem Wettkampfplatz in Gyűrűs, an beiden Seiten Zuschauer", maxEdge: 2400 },
  { src: "DJI_0733.jpg",  slug: "dron-naplemente-sorfal", alt: "Drónfelvétel: lovas sorfal a pályán a lenyugvó nap előtt, a Zalai-dombság erdőivel", alt_en: "Drone shot: a line of riders on the ground in front of the setting sun, with the forests of the Zala hills", alt_de: "Drohnenaufnahme: eine Reiterreihe auf dem Platz vor der untergehenden Sonne, mit den Wäldern des Zalaer Hügellands", maxEdge: 2400 },
  { src: "DJI_0748.jpg",  slug: "dron-palya",             alt: "Madártávlatból a gyűrűsi pálya, felsorakozott lovasokkal és a ménes épületeivel", alt_en: "Bird's-eye view of the ground in Gyűrűs, with riders lined up and the buildings of the stud", alt_de: "Der Platz in Gyűrűs aus der Vogelperspektive, mit aufgereihten Reitern und den Gebäuden des Gestüts", maxEdge: 2000 },
  { src: "_42A4702.jpg",  slug: "osveny-ugras-gyuru",     alt: "Hucul Ösvény feladat: lovas ugratás közben nyúl a gyűrűért", alt_en: "Hucul Trail task: a rider reaches for the ring while jumping", alt_de: "Aufgabe auf dem Huzulenpfad: ein Reiter greift im Sprung nach dem Ring", maxEdge: 2000 },
  { src: "_42A4658.jpg",  slug: "osveny-ugras-gyerek",     alt: "Gyerek lovas pej huculon ugrat a gyűrűs akadályon, a háttérben nézők a sátor alatt", alt_en: "A child rider on a bay Hucul jumps the ring obstacle, spectators under the tent in the background", alt_de: "Ein Kind reitet einen braunen Huzulen über das Ring-Hindernis, im Hintergrund Zuschauer unter dem Zelt", maxEdge: 1600 },
  { src: "_42A4694.jpg",  slug: "osveny-ugras-allo",      alt: "Hucul ló és lovasa ugrás közben a Hucul Ösvény akadályán", alt_en: "A Hucul horse and its rider jumping an obstacle on the Hucul Trail", alt_de: "Ein Huzulenpferd mit Reiter beim Sprung über ein Hindernis des Huzulenpfads", maxEdge: 1600 },
  { src: "_42A5066.jpg",  slug: "osveny-kosar",           alt: "Lovas kosárral a kezében a Hucul Ösvény ügyességi feladatán", alt_en: "A rider holding a basket during a skill task on the Hucul Trail", alt_de: "Reiter mit einem Korb in der Hand bei einer Geschicklichkeitsaufgabe des Huzulenpfads", maxEdge: 1600 },
  { src: "_42A4842.jpg",  slug: "istallo-lofej",          alt: "Pej ló feje közelről a világos istállóban, szalmán", alt_en: "Close-up of a bay horse's head in the bright stable, on straw", alt_de: "Kopf eines braunen Pferdes in Nahaufnahme im hellen Stall, auf Stroh", maxEdge: 1600 },
  { src: "_42A4903.jpg",  slug: "csiko-portre",           alt: "Fiatal csikó fejportréja, anyja mellett az istállóban", alt_en: "Head portrait of a young foal beside its mother in the stable", alt_de: "Kopfporträt eines jungen Fohlens neben seiner Mutter im Stall", maxEdge: 1600 },
  { src: "_42A4936.jpg",  slug: "lany-es-lo",             alt: "Fiatal nő narancssárga kötőfékes pej lóval a karám mellett", alt_en: "A young woman with a bay horse in an orange halter beside the paddock", alt_de: "Junge Frau mit einem braunen Pferd im orangefarbenen Halfter an der Koppel", maxEdge: 1600 },
  { src: "_42A4969.jpg",  slug: "palya-szalmabalak",      alt: "A versenypálya messziről: szalmabálák, lovasok és nézők a domboldal alatt", alt_en: "The competition ground from afar: straw bales, riders and spectators below the hillside", alt_de: "Der Wettkampfplatz aus der Ferne: Strohballen, Reiter und Zuschauer unterhalb des Hangs", maxEdge: 2000 },
  { src: "_42A5113.jpg",  slug: "hucul-fej-gyerek",       alt: "Sötét hucul ló feje közelről, nyergében gyerek lovas", alt_en: "Close-up of a dark Hucul horse's head, with a child rider in the saddle", alt_de: "Kopf eines dunklen Huzulenpferdes in Nahaufnahme, im Sattel ein Kind", maxEdge: 1600 },
  { src: "_42A5123.jpg",  slug: "gyerek-lovas",           alt: "Gyerek lovas fakó huculon, sisakban, a pálya szélén", alt_en: "A child rider in a helmet on a dun Hucul at the edge of the ground", alt_de: "Ein Kind mit Helm auf einem falbfarbenen Huzulen am Rand des Platzes", maxEdge: 1600 },
  { src: "_42A5141.jpg",  slug: "lovas-fako-hucul",       alt: "Fiatal nő fakó hucul lovon, a háttérben nézők", alt_en: "A young woman on a dun Hucul horse, spectators in the background", alt_de: "Junge Frau auf einem falbfarbenen Huzulenpferd, im Hintergrund Zuschauer", maxEdge: 1600 },
  { src: "_42A5249.jpg",  slug: "fekete-men",             alt: "Fekete hucul mén oldalról, kézen bemutatva a pályán", alt_en: "A black Hucul stallion from the side, shown in hand on the ground", alt_de: "Schwarzer Huzulenhengst von der Seite, an der Hand auf dem Platz vorgestellt", maxEdge: 2000 },
  { src: "_42A5260.jpg",  slug: "feher-lo-szabadon",      alt: "Fehér ló szabadon fut a bemutatón, mellette futó vezető", alt_en: "A white horse running loose at the show, a handler running beside it", alt_de: "Ein weißes Pferd läuft frei bei der Vorführung, daneben ein mitlaufender Pferdeführer", maxEdge: 1600 },
  { src: "_42A5300.jpg",  slug: "ket-lo-taj",             alt: "Két sötét hucul kézen vezetve, a háttérben a zalai erdős dombok", alt_en: "Two dark Huculs led in hand, the wooded hills of Zala in the background", alt_de: "Zwei dunkle Huzulen an der Hand geführt, im Hintergrund die bewaldeten Hügel von Zala", maxEdge: 2000 },
  { src: "_42A5306.jpg",  slug: "lo-es-no-bokeh",         alt: "Fekete ló feje és fiatal nő, aki a kantárt fogja, zöld háttérrel", alt_en: "A black horse's head and a young woman holding the bridle, against a green background", alt_de: "Kopf eines schwarzen Pferdes und eine junge Frau, die den Zaum hält, vor grünem Hintergrund", maxEdge: 2000 },
  { src: "_42A5352.jpg",  slug: "csikos-agaskodo",        alt: "Csikósbemutató: ágaskodó hucul ló a csikós mellett", alt_en: "Csikós show: a Hucul horse rearing beside the csikós", alt_de: "Csikós-Vorführung: ein sich aufbäumendes Huzulenpferd neben dem Csikós", maxEdge: 1600 },
  { src: "_42A5565.jpg",  slug: "csikos-portre",          alt: "Csikós hagyományos bő gatyában, kalapban, lova nyergében", alt_en: "A csikós in traditional wide trousers and a hat, in the saddle of his horse", alt_de: "Ein Csikós in traditioneller weiter Hose und Hut, im Sattel seines Pferdes", maxEdge: 2000 },
  { src: "_42A5578.jpg",  slug: "csikos-vagta-satrak",    alt: "Vágtató csikós a pályán, a háttérben sátrak és nézők", alt_en: "A csikós galloping on the ground, tents and spectators in the background", alt_de: "Ein Csikós im Galopp auf dem Platz, im Hintergrund Zelte und Zuschauer", maxEdge: 1600 },
  { src: "_42A5689.jpg",  slug: "csikos-vagta-kek",       alt: "Csikós vágtában, kék kendővel a kezében", alt_en: "A csikós at a gallop with a blue scarf in his hand", alt_de: "Ein Csikós im Galopp mit einem blauen Tuch in der Hand", maxEdge: 2000 },
  { src: "_42A5721.jpg",  slug: "aranyfeny-lovas-gyerek", alt: "Ellenfényben lovas és gyerek a ló mellett, esti aranyfényben", alt_en: "A rider and a child beside the horse, backlit in the golden evening light", alt_de: "Reiter und Kind neben dem Pferd im Gegenlicht, im goldenen Abendlicht", maxEdge: 1600 },
  { src: "_42A5725.jpg",  slug: "aranyfeny-sorfal",       alt: "Fiatal lovasok sorban, esti ellenfényben, porban", alt_en: "Young riders in a row, backlit in the evening, in the dust", alt_de: "Junge Reiter in einer Reihe, im abendlichen Gegenlicht, im Staub", maxEdge: 2400 },
  { src: "_BF_0833.jpg",  slug: "sorfal-eg",              alt: "Lovas sorfal a pályán, felette kék ég, mögötte erdős dombok", alt_en: "A line of riders on the ground, blue sky above and wooded hills behind", alt_de: "Eine Reiterreihe auf dem Platz, darüber blauer Himmel, dahinter bewaldete Hügel", maxEdge: 2400 },
  { src: "_BF_0843.jpg",  slug: "lovas-feher-ruha",       alt: "Fehér ruhás nő fogja egy hucul kantárját, a lovas gyerek a nyeregben", alt_en: "A woman in a white dress holds the bridle of a Hucul, the child rider in the saddle", alt_de: "Eine Frau im weißen Kleid hält den Zaum eines Huzulen, das reitende Kind im Sattel", maxEdge: 1600 },
  { src: "_BF_0809.jpg",  slug: "kozosseg-fozes",         alt: "Vendégek beszélgetnek a napernyők alatt, a háttérben bográcsok", alt_en: "Guests chatting under the parasols, cauldrons in the background", alt_de: "Gäste unterhalten sich unter den Sonnenschirmen, im Hintergrund Kessel", maxEdge: 1600 },
  { src: "_42A5268.jpg",  slug: "pej-lo-vezetve",         alt: "Pej ló kézen vezetve a bemutatón, nézők a kordonnál", alt_en: "A bay horse led in hand at the show, spectators at the rope barrier", alt_de: "Ein braunes Pferd an der Hand bei der Vorführung, Zuschauer an der Absperrung", maxEdge: 1600 },
];
